name: Update Changelog

permissions: write-all

on:
  push:
    branches:
      - main  # Adjust if your default branch is not `main`

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub openai

      - name: Fetch Pull Request Number
        id: fetch_pr
        run: |
          # Get the PR number from the commit message if available
          PR_NUMBER=$(git log -1 --pretty=%B | grep -oP '#\d+' | sed 's/#//')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Generate and Update Changelog
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: |
          python .github/actions/generate_and_update_changelog.py
